### ISSUE TITLE
Create transcripts.txt for Game of Thrones

### ISSUE THREAD

**Issue by benjisympa** [hbredin/pyannote-db-plumcot#18]
https://www.reddit.com/r/asoiaf/comments/79mzsj/spoilers_main_game_of_thrones_full_annotated/
http://gameofthronesfanon.wikia.com/wiki/Category:Transcripts
http://transcripts.foreverdreaming.org/viewtopic.php?t=7739

**Comment by benjisympa** [comment]
@aman Extracted : todo from this website ?

**Comment by hbredin** [comment]
Aman's Github username is not @aman...

**Comment by benjisympa** [comment]
Yes, Github doesn't purpose the right name sry, I will ask tomorrow

**Comment by aman-berhe** [comment]
I will do this. But the names of characters may need manual interference.
